# Generated by Django 5.0.7 on 2024-07-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='nome',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='carisma',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constituicao',
        ),
        migrations.RemoveField(
            model_name='character',
            name='destreza',
        ),
        migrations.RemoveField(
            model_name='character',
            name='forca',
        ),
        migrations.RemoveField(
            model_name='character',
            name='inteligencia',
        ),
        migrations.RemoveField(
            model_name='character',
            name='sabedoria',
        ),
        migrations.AddField(
            model_name='character',
            name='armor_class',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='cha',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='con',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='dex',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='inteligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='wis',
            field=models.IntegerField(default=10),
        ),
    ]
