# Generated by Django 5.0.7 on 2024-07-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_nome_character_name_remove_character_carisma_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='nome',
            new_name='name',
        ),
    ]
