# Generated by Django 5.0.7 on 2024-07-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_nome_monster_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participant_monsters', models.JSONField()),
                ('participant_characters', models.JSONField()),
            ],
        ),
    ]
