# Generated by Django 5.0.7 on 2024-07-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_rename_battles_battle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='participant_characters',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='battle',
            name='participant_monsters',
            field=models.JSONField(null=True),
        ),
    ]
