# Generated by Django 5.0.7 on 2024-07-16 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_battle_participant_characters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='participant_characters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.character'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='participant_monsters',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.monster'),
        ),
    ]
